### ISSUE TITLE
Prettier dependency set

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/crystal-ball.github.io#17]
## Overview

Prettier 1.17 introduced shared package configs which is 🎉

Create a Crystal Ball dependency set for including Prettier with a shared config in projects.

### Tasks

- [x] Create package `@crystal-ball/prettier-base`
- [x] Create shared configs
- [x] Include base dep set
- [x] Document usage in README
  - [`prettier`](https://www.npmjs.com/package/prettier)
