### ISSUE TITLE
Storybook dependencies set

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/crystal-ball.github.io#22]
## Overview

Provide minimum configs and dependencies for using Storybook in projects.

### Tasks

- [ ] Create `@crystal-ball/storybook-base` package
- [ ] Include base sets of configuration for setting up Storybook.
- [ ] Require base dependencies
  - ??? - determine *minimum* set of base deps.
