### ISSUE TITLE
Client testing dependency set

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/crystal-ball.github.io#23]
## Overview
Provide minimum configs and dependencies for testing client projects with Jest, React Testing Library and Cypress.

### Tasks

- [ ] Create `@crystal-ball/client-testing-base` package
- [ ] Determine shared configs and scripts...
- [ ] Determine  *minimum* set of base deps...
