### ISSUE TITLE
Services testing dependency set

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/crystal-ball.github.io#24]
## Overview
Provide minimum configs and dependencies for testing Node.js service projects with Jest and Mountebank.

### Tasks

- [ ] Create `@crystal-ball/service-testing-base` package
- [ ] Determine shared configs and scripts...
- [ ] Determine  *minimum* set of base deps...
