### ISSUE TITLE
Authoring packages

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/crystal-ball.github.io#44]
Code authoring workflow includes writing and commiting code.

- [x] Prettier base package
- [x] ESlint base package
- [x] Commitizen base package
